const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getProjects: () => ipcRenderer.invoke('get-projects'),
  createProject: (payload) => ipcRenderer.invoke('create-project', payload),
  createSubProject: (payload) => ipcRenderer.invoke('create-subproject', payload),
  deleteProject: (id) => ipcRenderer.invoke('delete-project', id),
  getIssues: (projectId) => ipcRenderer.invoke('get-issues', projectId),
  saveIssue: (projectId, issue) => ipcRenderer.invoke('save-issue', projectId, issue),
  deleteIssue: (projectId, issueId) => ipcRenderer.invoke('delete-issue', projectId, issueId),
  getMethodologies: () => ipcRenderer.invoke('get-methodologies'),
  createMethodology: (payload) => ipcRenderer.invoke('create-methodology', payload),
  createMethodologyTask: (payload) => ipcRenderer.invoke('create-methodology-task', payload),
  updateMethodologyTask: (payload) => ipcRenderer.invoke('update-methodology-task', payload),
  updateMethodology: (payload) => ipcRenderer.invoke('update-methodology', payload),
  deleteMethodology: (id) => ipcRenderer.invoke('delete-methodology', id),
  deleteMethodologyTask: (id) => ipcRenderer.invoke('delete-methodology-task', id),
  getUserProfile: () => ipcRenderer.invoke('get-user-profile'),
  createUserProfile: (payload) => ipcRenderer.invoke('create-user-profile', payload),
  updateUserProfile: (payload) => ipcRenderer.invoke('update-user-profile', payload),
  getNotes: (projectId) => ipcRenderer.invoke('get-notes', projectId),
  saveNote: (projectId, note) => ipcRenderer.invoke('save-note', projectId, note),
  deleteNote: (projectId, noteId) => ipcRenderer.invoke('delete-note', projectId, noteId),
  generateReport: (payload) => ipcRenderer.invoke('generate-report', payload),
  getReportPreview: (payload) => ipcRenderer.invoke('get-report-preview', payload),
  getSmtpSettings: () => ipcRenderer.invoke('get-smtp-settings'),
  saveSmtpSettings: (payload) => ipcRenderer.invoke('save-smtp-settings', payload),
  getEmailHistory: (payload) => ipcRenderer.invoke('get-email-history', payload),
  sendIssueReportEmail: (payload) => ipcRenderer.invoke('send-issue-report-email', payload),
  sendProjectReportEmail: (payload) => ipcRenderer.invoke('send-project-report-email', payload),
  selectMedia: (mediaType) => ipcRenderer.invoke('select-media', mediaType),
});
